# Generated by Django 4.1.7 on 2023-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
