# Generated by Django 4.1.7 on 2023-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="group",
        ),
        migrations.AddField(
            model_name="plan",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
    ]
