# Generated by Django 4.1.7 on 2023-03-08 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0002_remove_plan_group_plan_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"permissions": [("can_do", "Can do sdfs")]},
        ),
    ]
