# Generated by Django 4.1.7 on 2023-03-09 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0004_alter_membership_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={},
        ),
    ]
